/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    CustomShopWizard: typeof import('./../components/organisms/CustomShopWizard/index.vue')['default']
    LBadge: typeof import('./../components/atoms/LBadge.vue')['default']
    LButton: typeof import('./../components/atoms/LButton.vue')['default']
    PageWrapper: typeof import('./../components/layout/PageWrapper.vue')['default']
    ProductCard: typeof import('./../components/molecules/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Step1Body: typeof import('./../components/organisms/CustomShopWizard/Step1Body.vue')['default']
    Step2Wood: typeof import('./../components/organisms/CustomShopWizard/Step2Wood.vue')['default']
    Step3Craft: typeof import('./../components/organisms/CustomShopWizard/Step3Craft.vue')['default']
    Step4Hardware: typeof import('./../components/organisms/CustomShopWizard/Step4Hardware.vue')['default']
    Step5Upload: typeof import('./../components/organisms/CustomShopWizard/Step5Upload.vue')['default']
    Step6Summary: typeof import('./../components/organisms/CustomShopWizard/Step6Summary.vue')['default']
    StepIndicator: typeof import('./../components/molecules/StepIndicator.vue')['default']
  }
}
